// -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING --
//
// THE CONTENTS OF THIS FILE IS GENERATED BY CODE AND
// ANY MODIFICATIONS WILL BE OVERWRITTEN
//
// -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING --

// %BANNER_BEGIN%
// ---------------------------------------------------------------------
// %COPYRIGHT_BEGIN%
//
// Copyright (c) 2018 Magic Leap, Inc. All Rights Reserved.
// Use of this file is governed by the Creator Agreement, located
// here: https://id.magicleap.com/creator-terms
//
// %COPYRIGHT_END%
// ---------------------------------------------------------------------
// %BANNER_END%

// %SRC_VERSION%: 2

#include <SceneBase.h>
#include <SceneDescriptor.h>
#include <SceneManager.h>

#include <assert.h>

SceneBase::SceneBase(ExtendedSceneManager* const extendedSceneManager, lumin::Node* const root)
: extendedSceneManager_(extendedSceneManager),
  root_(root) {
  assert(extendedSceneManager);
  assert(root);
}

SceneBase::~SceneBase() {
  assert(root_ == nullptr);
}

lumin::Node* SceneBase::getRoot() const {
  return root_;
}

ExtendedSceneManager* SceneBase::getExtendedSceneManager() const {
  return extendedSceneManager_;
}

ExtendedPrefabManager* SceneBase::getExtendedPrefabManager() const {
  return extendedSceneManager_->getExtendedPrefabManager();
}
