# Generated Makefile -- DO NOT EDIT!

AR=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/tools/toolchains/llvm-8/bin/aarch64-linux-android-gcc-ar.exe
COMPILER_PREFIX=
CXX=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/tools/toolchains/llvm-8/bin/aarch64-linux-android-clang++
HOST=win64
MLSDK=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1
RM=rm
SHARED_PREFIX=lib
SPEC=debug_lumin_clang-8.0_aarch64
TOUCH=touch
app_framework_ARFLAGS=
app_framework_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework
app_framework_CPPFLAGS=-I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_LUMIN -DGLM_FORCE_CTOR_INIT=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
app_framework_CXXFLAGS=--sysroot=$(MLSDK)/lumin/sysroot -march=armv8-a -mcpu=cortex-a57+crypto -fPIC -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -g -fno-limit-debug-info -O0 -nostdinc++ -I$(MLSDK)/lumin/stl/libc++-8/include -fexceptions -std=c++11
app_framework_OUTPUT=$(app_framework_BASE)/.out/$(SPEC)
assimp_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
gflags_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
glad_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
glm_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
imgui_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
stb_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external

$(app_framework_OUTPUT)/libapp_framework.a : $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Linking\ static\ library\ 'libapp_framework.a'...
	$(ECHO) $(RM) -f $(app_framework_OUTPUT)/libapp_framework.a
	$(ECHO) cd $(app_framework_OUTPUT) && $(AR) crs libapp_framework.a obj.app_framework/src/device/graphics_context.cpp.o obj.app_framework/src/application.cpp.o obj.app_framework/src/cli_args_parser.cpp.o obj.app_framework/src/convert.cpp.o obj.app_framework/src/node.cpp.o obj.app_framework/src/gui.cpp.o obj.app_framework/src/render/program.cpp.o obj.app_framework/src/render/geometry_program.cpp.o obj.app_framework/src/render/material.cpp.o obj.app_framework/src/render/renderer.cpp.o obj.app_framework/src/render/buffer.cpp.o obj.app_framework/src/render/variable.cpp.o obj.app_framework/src/render/mesh.cpp.o obj.app_framework/src/render/texture.cpp.o obj.app_framework/src/render/render_target.cpp.o obj.app_framework/src/registry.cpp.o obj.app_framework/src/resource_pool.cpp.o obj.app_framework/src/input/ml_input_handler.cpp.o obj.app_framework/src/input/input_command_handler.cpp.o $(app_framework_ARFLAGS)
	$(ECHO) $(TOUCH) $(app_framework_OUTPUT)/libapp_framework.a

$(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.o : $(app_framework_BASE)/src/device/graphics_context.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'graphics_context.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/device/graphics_context.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/device/graphics_context.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o : $(app_framework_BASE)/src/application.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'application.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/application.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/application.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o : $(app_framework_BASE)/src/cli_args_parser.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'cli_args_parser.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/cli_args_parser.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/cli_args_parser.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o : $(app_framework_BASE)/src/convert.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'convert.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/convert.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/convert.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o : $(app_framework_BASE)/src/node.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'node.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/node.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/node.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o : $(app_framework_BASE)/src/gui.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'gui.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/gui.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/gui.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o : $(app_framework_BASE)/src/render/program.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'program.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/program.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/program.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o : $(app_framework_BASE)/src/render/geometry_program.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'geometry_program.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/geometry_program.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/geometry_program.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o : $(app_framework_BASE)/src/render/material.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'material.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/material.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/material.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o : $(app_framework_BASE)/src/render/renderer.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'renderer.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/renderer.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/renderer.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o : $(app_framework_BASE)/src/render/buffer.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'buffer.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/buffer.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/buffer.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o : $(app_framework_BASE)/src/render/variable.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'variable.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/variable.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/variable.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o : $(app_framework_BASE)/src/render/mesh.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'mesh.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/mesh.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/mesh.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o : $(app_framework_BASE)/src/render/texture.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'texture.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/texture.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/texture.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o : $(app_framework_BASE)/src/render/render_target.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'render_target.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/render/render_target.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/render/render_target.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o : $(app_framework_BASE)/src/registry.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'registry.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/registry.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/registry.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o : $(app_framework_BASE)/src/resource_pool.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'resource_pool.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/resource_pool.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/resource_pool.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o : $(app_framework_BASE)/src/input/ml_input_handler.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'ml_input_handler.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/input/ml_input_handler.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/input/ml_input_handler.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o : $(app_framework_BASE)/src/input/input_command_handler.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'input_command_handler.cpp'...
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -c $(app_framework_BASE)/src/input/input_command_handler.cpp -o $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o -MD -MP -MF $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)
	$(ECHO) echo $(app_framework_BASE)/src/input/input_command_handler.cpp : >> $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d

-include $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d

app_framework-clean :: 
	$(INFO) Cleaning\ app_framework...
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/libapp_framework.a $(app_framework_OUTPUT)/app_framework.sym $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/device/graphics_context.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/bin/libc++_shared.so $(app_framework_OUTPUT)/bin/libassimpd.so.4

app_framework-all :: -make-directories $(app_framework_OUTPUT)/libapp_framework.a

