# Generated Makefile -- DO NOT EDIT!

AR=C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/lib.exe
COMPILER_PREFIX=
CXX=C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe
DEPGEN=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/tools/mabu/tools/win/depgen.py
HOST=win64
MLSDK=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1
PYTHON=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/tools/python3/python.exe
RM=rm
SHARED_PREFIX=
SPEC=debug_win_msvc-2017-15.9_x64
app_framework_ARFLAGS=
app_framework_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework
app_framework_CPPFLAGS=-I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.16.27023/ATLMFC/include -IC:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC/14.16.27023/include -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.18362.0/ucrt -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.18362.0/shared -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.18362.0/um -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.18362.0/winrt -IC:/Program\ Files\ \(x86\)/Windows\ Kits/10/include/10.0.18362.0/cppwinrt -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
app_framework_CXXFLAGS=-MDd -Gm- -ZI -Od -EHsc -W2
app_framework_OUTPUT=$(app_framework_BASE)/.out/$(SPEC)
assimp_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
gflags_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
glad_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
glfw_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
glm_comp_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
imgui_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external
stb_BASE=C:/Users/snowy/MagicLeap/mlsdk/v0.24.1/samples/c_api/app_framework/external

$(app_framework_OUTPUT)/app_framework.lib : $(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Linking\ static\ library\ 'app_framework.lib'....
	$(ECHO) $(RM) -f $(app_framework_OUTPUT)/app_framework.lib
	$(ECHO) cd $(app_framework_OUTPUT) && $(AR) -nologo -out:app_framework.lib obj.app_framework/src/host/graphics_context.cpp.o obj.app_framework/src/application.cpp.o obj.app_framework/src/cli_args_parser.cpp.o obj.app_framework/src/convert.cpp.o obj.app_framework/src/node.cpp.o obj.app_framework/src/gui.cpp.o obj.app_framework/src/render/program.cpp.o obj.app_framework/src/render/geometry_program.cpp.o obj.app_framework/src/render/material.cpp.o obj.app_framework/src/render/renderer.cpp.o obj.app_framework/src/render/buffer.cpp.o obj.app_framework/src/render/variable.cpp.o obj.app_framework/src/render/mesh.cpp.o obj.app_framework/src/render/texture.cpp.o obj.app_framework/src/render/render_target.cpp.o obj.app_framework/src/registry.cpp.o obj.app_framework/src/resource_pool.cpp.o obj.app_framework/src/input/ml_input_handler.cpp.o obj.app_framework/src/input/input_command_handler.cpp.o $(app_framework_ARFLAGS)

$(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.o : $(app_framework_BASE)/src/host/graphics_context.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'graphics_context.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/host/graphics_context.cpp $(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/host/graphics_context.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o : $(app_framework_BASE)/src/application.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'application.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/application.cpp $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/application.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o : $(app_framework_BASE)/src/cli_args_parser.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'cli_args_parser.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/cli_args_parser.cpp $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/cli_args_parser.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o : $(app_framework_BASE)/src/convert.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'convert.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/convert.cpp $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/convert.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o : $(app_framework_BASE)/src/node.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'node.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/node.cpp $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/node.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o : $(app_framework_BASE)/src/gui.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'gui.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/gui.cpp $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/gui.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o : $(app_framework_BASE)/src/render/program.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'program.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/program.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/program.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o : $(app_framework_BASE)/src/render/geometry_program.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'geometry_program.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/geometry_program.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/geometry_program.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o : $(app_framework_BASE)/src/render/material.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'material.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/material.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/material.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o : $(app_framework_BASE)/src/render/renderer.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'renderer.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/renderer.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/renderer.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o : $(app_framework_BASE)/src/render/buffer.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'buffer.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/buffer.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/buffer.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o : $(app_framework_BASE)/src/render/variable.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'variable.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/variable.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/variable.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o : $(app_framework_BASE)/src/render/mesh.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'mesh.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/mesh.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/mesh.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o : $(app_framework_BASE)/src/render/texture.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'texture.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/texture.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/texture.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o : $(app_framework_BASE)/src/render/render_target.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'render_target.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/render/render_target.cpp $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/render/render_target.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o : $(app_framework_BASE)/src/registry.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'registry.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/registry.cpp $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/registry.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o : $(app_framework_BASE)/src/resource_pool.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'resource_pool.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/resource_pool.cpp $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/resource_pool.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o : $(app_framework_BASE)/src/input/ml_input_handler.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'ml_input_handler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/input/ml_input_handler.cpp $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/input/ml_input_handler.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d
$(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o : $(app_framework_BASE)/src/input/input_command_handler.cpp $(app_framework_BASE)/app_framework.mabu $(MLSDK)/.metadata/components/ml_sdk.comp $(MLSDK)/.metadata/components/ml_sdk_common.comp $(MLSDK)/samples/c_api/app_framework/common.comp $(MLSDK)/samples/c_api/app_framework/external/assimp.comp $(MLSDK)/samples/c_api/app_framework/external/gflags.comp $(MLSDK)/samples/c_api/app_framework/external/glfw.comp $(MLSDK)/samples/c_api/app_framework/external/glm.comp $(MLSDK)/tools/mabu/data/components/OpenGL.comp $(MLSDK)/tools/mabu/data/components/stdc++.comp $(MLSDK)/tools/mabu/data/configs/debug.config $(MLSDK)/tools/mabu/data/options/debug/on.option $(MLSDK)/tools/mabu/data/options/magicleap.option $(MLSDK)/tools/mabu/data/options/optimize/off.option $(MLSDK)/tools/mabu/data/options/package/debuggable/on.option $(MLSDK)/tools/mabu/data/options/runtime/shared.option $(MLSDK)/tools/mabu/data/options/warn/on.option
	$(INFO) \[app_framework\]\ Compiling\ 'input_command_handler.cpp'...
	$(ECHO) $(PYTHON) $(DEPGEN) $(app_framework_BASE)/src/input/input_command_handler.cpp $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o -I$(app_framework_BASE)/include -I$(app_framework_BASE)/include/app_framework/render -I$(glad_BASE)/glad/include -I$(imgui_BASE)/imgui-1.68 -I$(stb_BASE)/stb-master/ -I$(glfw_comp_BASE)/package/$(SPEC)/include -I$(MLSDK)/include -I$(assimp_comp_BASE)/package/$(SPEC)/include -I$(gflags_comp_BASE)/package/$(SPEC)/include -I$(glm_comp_BASE)/glm-0.9.9.4 -DML_WINDOWS -DWIN32_LEAN_AND_MEAN -DNOGDI -D_USE_MATH_DEFINES -DGLM_FORCE_CTOR_INIT=1 -DGLFW_INCLUDE_NONE=1 -DML_USE_HIGH_PERFORMANCE_GPU=1 -DML_DEFAULT_LOG_TAG=\"app_framework\"
	$(ECHO) $(COMPILER_PREFIX) $(CXX) -nologo -TP -c $(app_framework_BASE)/src/input/input_command_handler.cpp -Fo$(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o -FS -Fd$(app_framework_OUTPUT)/app_framework.pdb $(app_framework_CPPFLAGS) $(app_framework_CXXFLAGS)

-include $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d

app_framework-clean :: 
	$(INFO) Cleaning\ app_framework...
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/app_framework.lib $(app_framework_OUTPUT)/app_framework.ilk $(app_framework_OUTPUT)/app_framework.idb $(app_framework_OUTPUT)/app_framework.pdb $(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/host/graphics_context.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/application.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/cli_args_parser.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/convert.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/node.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/gui.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/program.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/geometry_program.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/material.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/renderer.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/buffer.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/variable.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/mesh.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/render/texture.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/render/render_target.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/registry.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/resource_pool.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.o $(app_framework_OUTPUT)/obj.app_framework/src/input/ml_input_handler.cpp.d $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.o
	$(ECHO) $(RM) -rf $(app_framework_OUTPUT)/obj.app_framework/src/input/input_command_handler.cpp.d $(app_framework_OUTPUT)/$(SPEC)/glfw3d.dll $(app_framework_OUTPUT)/$(SPEC)/assimp-vc140-mtd.dll $(app_framework_OUTPUT)/$(SPEC)/gflags_nothreads_debug.dll

app_framework-all :: -make-directories $(app_framework_OUTPUT)/app_framework.lib

