// -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING --
//
// THE CONTENTS OF THIS FILE IS GENERATED BY CODE AND
// ANY MODIFICATIONS WILL BE OVERWRITTEN
//
// -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING --

// %BANNER_BEGIN%
// ---------------------------------------------------------------------
// %COPYRIGHT_BEGIN%
//
// Copyright (c) 2018 Magic Leap, Inc. All Rights Reserved.
// Use of this file is governed by the Creator Agreement, located
// here: https://id.magicleap.com/creator-terms
//
// %COPYRIGHT_END%
// ---------------------------------------------------------------------
// %BANNER_END%

// %SRC_VERSION%: 2

#include <PrefabDescriptor.h>

PrefabDescriptor::PrefabDescriptor(int index, const char* name, const char* id, const char* objectModelPath, const char* resourceModelPath)
:
  index_(index),
  name_(name),
  id_(id),
  objectModelPath_(objectModelPath),
  resourceModelPath_(resourceModelPath) {
 }

int PrefabDescriptor::getIndex() const {
  return index_;
}

const std::string& PrefabDescriptor::getName() const {
  return name_;
}

const std::string& PrefabDescriptor::getId() const {
  return id_;
}

const std::string& PrefabDescriptor::getObjectModelPath() const {
  return objectModelPath_;
}

const std::string& PrefabDescriptor::getResourceModelPath() const {
  return resourceModelPath_;
}
