// -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING --
//
// THE CONTENTS OF THIS FILE IS GENERATED BY CODE AND
// ANY MODIFICATIONS WILL BE OVERWRITTEN
//
// -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING -- WARNING --

// %BANNER_BEGIN%
// ---------------------------------------------------------------------
// %COPYRIGHT_BEGIN%
//
// Copyright (c) 2018 Magic Leap, Inc. All Rights Reserved.
// Use of this file is governed by the Creator Agreement, located
// here: https://id.magicleap.com/creator-terms
//
// %COPYRIGHT_END%
// ---------------------------------------------------------------------
// %BANNER_END%

// %SRC_VERSION%: 2

#pragma once

class PrefabDescriptor;
class PrefabManager;
class ExtendedPrefabManager;

#include <lumin/node/Node.h>

#include <vector>

class PrefabBase {
public:

  typedef std::vector<std::string> NodeReferences;

public:

  virtual const PrefabDescriptor& getPrefabDescriptor() const = 0;
  virtual const NodeReferences& getNodeReferences() const = 0;

  lumin::Node* getRoot() const;

protected:

  ExtendedPrefabManager* const extendedPrefabManager_ = nullptr;
  lumin::Node* root_ = nullptr;

  friend class ::PrefabManager;
  friend class ::ExtendedPrefabManager;
  PrefabBase(ExtendedPrefabManager* esm, lumin::Node* aRoot);
  virtual ~PrefabBase();

  PrefabBase() = delete;
  PrefabBase(const PrefabBase&) = delete;
  PrefabBase(const PrefabBase&&) = delete;
  virtual void deleteNodeTree();
};
